CREATE DATABASE IF NOT EXISTS companydb;

USE companydb;

CREATE TABLE empleados(
    id INT(11) NOT NULL AUTO_INCREMENT,
    name VARCHAR(45) DEFAULT NULL,
    salary INT(5) DEFAULT NULL,
    PRIMARY KEY(id)
);

DESCRIBE empleados;

INSERT INTO empleados VALUES (1, "JUAN", 2500), (2, "JOSE", 3000), (3, "LUCAS", 2000);